FROM ubuntu

MAINTAINER sujoychakraborty@gmail.com

WORKDIR /usr/apps/hello-docker/

RUN apt-get update -y

RUN apt-get install nodejs -y

RUN apt-get install npm -y

RUN npm install -g http-server

ADD . /usr/apps/hello-docker/

ADD index.html /usr/apps/hello-docker/index.html

CMD ["http-server", "-s"]
